// Writes docs/RULES.md from the rule catalogue compiled into the extension.
//
// The catalogue is the documentation: maintaining a second copy by hand is how a
// reference ends up describing rules the extension no longer has. CI regenerates
// this file and fails if the result differs from what is committed.
//
//   npm run docs
import * as fs from 'fs';
import * as path from 'path';

import { RULES } from '../src/core/analyze';

const OUT = path.join('docs', 'RULES.md');

const scopes: Array<{ id: 'syntax' | 'master' | 'media' | 'cross' | 'dash'; title: string; blurb: string }> = [
  { id: 'syntax', title: 'Structure', blurb: 'Rules about the file being a playlist at all.' },
  { id: 'master', title: 'Master playlist', blurb: 'Rules about the ladder and the rendition groups.' },
  { id: 'media', title: 'Media playlist', blurb: 'Rules about segments, timing, keys and the live window.' },
  {
    id: 'cross',
    title: 'Across playlists',
    blurb:
      'Rules that need the master and its renditions at once, from `HLS Lens: Check Renditions Together`. Every rendition is a valid playlist on its own; these are the ways they can disagree with each other.',
  },
  {
    id: 'dash',
    title: 'DASH',
    blurb:
      'Rules for an `.mpd`. The extension stays HLS-first, but the same stream is usually packaged both ways from one mezzanine, and the defects are the same ones: a declared duration the segments do not fill, a hole in the timeline, a live manifest with no clock.',
  },
];

const lines: string[] = [
  '<!-- Generated by `npm run docs`. Do not edit by hand. -->',
  '',
  '# Rules',
  '',
  `HLS Lens ships ${RULES.length} rules. Most read one manifest — the claims it makes — and point at the line you have to fix;`,
  'the `cross/*` rules read the master and its renditions together and report on the variant line of the master.',
  'For the defects that need the segment bytes (a gap that no `EXT-X-DISCONTINUITY` declares, a 1080p rung that codes 720p),',
  'run the deep check, which brings [segcheck](https://github.com/Allan-Nava/segcheck) findings into the same Problems panel.',
  '',
  'Severity maps onto the editor: **error** is a broken stream or a spec violation, **warning** is something players tolerate',
  'and viewers pay for, **hint** is advisory (mostly from the Apple HLS authoring specification).',
  '',
  'Ids are stable: they are what `hlsLens.diagnostics.skip` pins.',
  '',
  '| Rule | Severity | Checks that |',
  '|---|---|---|',
];
for (const rule of RULES) {
  lines.push(`| [\`${rule.id}\`](#${anchor(rule.id)}) | ${rule.severity} | ${rule.title} |`);
}
lines.push('');

for (const scope of scopes) {
  const rules = RULES.filter((r) => r.scope === scope.id);
  if (rules.length === 0) continue;
  lines.push(`## ${scope.title}`, '', scope.blurb, '');
  for (const rule of rules) {
    lines.push(`### \`${rule.id}\``, '', `**${rule.title}** · ${rule.severity}`, '', rule.rationale, '');
  }
}

fs.mkdirSync('docs', { recursive: true });
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`wrote ${OUT} (${RULES.length} rules)`);

/** anchor renders the GitHub heading anchor of a backticked rule id. */
function anchor(id: string): string {
  return id.toLowerCase().replace(/\//g, '');
}
